### ISSUE TITLE
[bug] It's not possible to install entropyxyz/cli package

### ISSUE THREAD

**Issue by ipohosov** [entropyxyz/cli#279]
Node version - 22.11.0
Ubuntu 22.04

<img width="890" alt="Screenshot 2024-11-01 at 11 59 48" src="https://github.com/user-attachments/assets/1fe12b28-2247-4cf5-bc4a-c4dfbbdb406d">

**Comment by rh0delta** [comment]
@ipohosov thanks for filing the issue, we are aware of this issue and found that it is currently due to an incompatible node version for the CLI. If you are using a node version manager like `nvm` you can install the node version v20.10.0 and that should temporarily fix the issue you are experiencing with the install. We are currently looking into the compatibility issue, and should have a solution in the next release of the CLI (v0.0.4)
